package lesson13.dataEnum;

public enum Names {
    ANDRAY, SERGAY, SASHA, ARTYOM, DMITRIY, MAXIM, ROMAN, IGOR, ILYA, ZHENYA, YAROSLAVA, MARIA,
    VIKA, DASHA, DIANA, NASTYA, ANZHELA, SEMYON, MIRA, ROZA
}
