package lesson13.dataEnum;

public enum Surnames {
    SMITH, JOHNSON, JONES, BROWN, DAVIS, MILLER, WILSON, MOORE, ANDERSON, JACKSON, WHITE, HARRIS, COX, MURPHY, HOWARD,
    WARD, MORGAN, FREEMAN, LEE, KING, LOPEZ
}
