package lesson20.enums;

public enum EmployeeSurnames {
    SMITH, JONSON, JONES, BROWN, DAVIS, MILLER, WILSON, MOORE, ANDERSON, JACKSON, WHITE, HARRISON, COX,
    MURPHY, HOWARD, WARD, MORGAN, FREEMAN, LEE, KING
}
